---
- name: Proxmox setup
  hosts: localhost
  gather_facts: true
  roles:
    - serhii9132.proxmox_bootstrap.storage
    - serhii9132.proxmox_bootstrap.apt_repos
    - serhii9132.proxmox_bootstrap.nag_screen
    - serhii9132.base_layer.common
    - serhii9132.base_layer.utilities
    - serhii9132.proxmox_bootstrap.ssh
    - serhii9132.proxmox_bootstrap.accounts
    - serhii9132.base_layer.bash_aliases
